Assignment1/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Data;
using Assignment1.Models;

namespace Assignment1.Controllers
{
    public class LoginController : Controller
    {
        //
        // GET: /Login/

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User user)
        {
            string str = @"Data Source=.;Initial Catalog=assignment1;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework";

            using (SqlConnection con = new SqlConnection(str))
            {
                //SqlCommand cmd = new SqlCommand("Insert into Users UserId, Name, username, Pass, Email, number, createdDate, RoleId values (@UserId, @Name, @username, @Pass, @Email, @number, @createdDate, @RoleId)", con);

                SqlCommand cmd = new SqlCommand("Admin", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@username", user.username);
                cmd.Parameters.AddWithValue("@Pass", user.Pass);
                //cmd.Parameters.AddWithValue("@RoleId", user.RoleId);
                con.Open();
                cmd.ExecuteNonQuery();
                con.Close();
            
            }

            return RedirectToAction("Admin", "Admin");
            //return View();

            
        }

        public ActionResult Admin()
        {
           return View();
        }

    }
}

Assignment1/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Assignment1.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace Assignment1.Controllers
{
    public class RegisterController : Controller
    {
        //
        // GET: /Register/

        assignment1Entities userdb = new assignment1Entities();
        public ActionResult Register()
        {
            assignment1Entities myentity = new assignment1Entities();
            var getRoleName = myentity.Roles.ToList();
            SelectList list = new SelectList(getRoleName, "RoleId", "RoleName");
            ViewBag.RoleListName = list;
            return View();
        }

        public ActionResult Insertdate()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Insertdate(User user)
        {
          //  userdb.InsertUser(user.UserId, user.Name, user.username, user.Pass, user.Email, user.number, user.createdDate, user.RoleId);

            assignment1Entities myentity = new assignment1Entities();
            var getRoleName = myentity.Roles.ToList();
            SelectList list = new SelectList(getRoleName, "RoleId", "RoleName");
            ViewBag.RoleListName = list;

            string str = @"Data Source=.;Initial Catalog=assignment1;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework";
            DateTime date = Convert.ToDateTime(DateTime.Now.ToShortDateString());

            using (SqlConnection con = new SqlConnection(str))
            {
                //SqlCommand cmd = new SqlCommand("Insert into Users UserId, Name, username, Pass, Email, number, createdDate, RoleId values (@UserId, @Name, @username, @Pass, @Email, @number, @createdDate, @RoleId)", con);

                SqlCommand cmd = new SqlCommand("InsertUsers", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@UserId", user.UserId);
                cmd.Parameters.AddWithValue("@Name", user.Name);
                cmd.Parameters.AddWithValue("@username", user.username);
                cmd.Parameters.AddWithValue("@Pass", user.Pass);
                cmd.Parameters.AddWithValue("@Email", user.Email);
                cmd.Parameters.AddWithValue("@number", user.number);
                cmd.Parameters.AddWithValue("@createdDate", date);
                cmd.Parameters.AddWithValue("@RoleId", user.RoleId);
                con.Open();
                cmd.ExecuteNonQuery();
                con.Close();
            }
            return View();
        }

        //public ActionResult Insertdate(User uesr)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        ds.Users(user)
        //    }
        //    return View();
        //}

    }
}

Assignment1/Views/Login/Login.cshtml
@model Assignment1.Models.User

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm()) {  
    @Html.ValidationSummary(true)  
  
  
    <fieldset>  
        <legend>User</legend>  
        @Html.AntiForgeryToken()  
        @if (ViewBag.Message != null)  
        {  
  
            <div style="border:solid 1px green">  
                 @ViewBag.Message  
            </div>  
        }  
        <div class="editor-label">  
          @Html.LabelFor(model => model.username)  
      </div>  
      <div class="editor-field">  
          @Html.EditorFor(model => model.username)  
          @Html.ValidationMessageFor(model => model.username)  
      </div>  
        <div class="editor-label">  
         @Html.LabelFor(model => model.Pass)  
      </div>  
      <div class="editor-field">  
          @Html.EditorFor(model => model.Pass)  
          @Html.ValidationMessageFor(model => model.Pass)  
      </div>  

          <div class="editor-label" hidden>  
         @Html.LabelFor(model => model.RoleId)  
      </div>  
      <div class="editor-field" hidden>  
          @Html.EditorFor(model => model.RoleId)  
          @Html.ValidationMessageFor(model => model.RoleId)  
      </div>  
      <p>  
          <input type="submit" value="Login" />  
      </p>  
   </fieldset>  
}  
  
  
<div>  
   @Html.ActionLink("Back to List", "Register")  
</div>  